LEVELS = [
    ('nivel1.tga',      'nivel1',),
    ('phil_7.tga',      'phil_7',),
    ('tim_2.tga',       'tim_2',),
    ('phil_2.tga',      'phil_"',),
    ('phil_13.tga',     'phil_13',),
    ('prueba.tga',     'prueba',),
    ('phil_4.tga',     'phil_4',),
    ('phil_11.tga',     'phil_11',),
    ('phil_15.tga',     'phil_15',),
    
    ('pekuja_3.tga',    'pekuja_3',),
    ('tim_4.tga',       'tim_4',),
    ('phil_14.tga',     'phil_14',),
    ('drpetter_1.tga',     'drpetter_1',),
    ('pekuja_2.tga',     'pekuja_2',),
    ('phil_9.tga',     'phil_9',),
    ('fydo_1.tga',     'fydo_1',),
    ('phil_8.tga',      'phil_8',),
    ('phil_3.tga',     'phil_3',),
    
    ('tee_1.tga',     'tee_1',),
    ('tim_1.tga',     'tim_1',),
    ('eugman_1.tga',     'eugman_1',),
    ('phil_6.tga',     'phil_6',),
    ('phil_12.tga',     'phil_12',),
    ('pekuja_1.tga',    'pekuja_1',),
    ('phil_5.tga',      'phil_5',),
    ('phil_10.tga',     'phil_10',),
    ('boss_1.tga',      'boss_1',),
]
