#!/bin/sh
#Para aplicar los cambios interactivamente permitiendo comentario por fichero
awk '
BEGIN{
    FS=":"
    comando = "git commit -a --dry-run"
    while (comando|getline)
        if ($1~"modified" || $1~"new file"){
            gsub("^ *", "", $2)
            printf "Mensaje para %s: ", $2
            getline mensaje
            a[$2] = mensaje
        }
    close(commando)
    if (length(a)){
        for (i in a)
            system("git commit -m \"" a[i] "\" \"" i "\"")
        print "Commit finalizado"
        print "Intentando push"
        errorpush = system("git push")
        if (errorpush){
            print "No se ha podido push directo, intentando pull"
            errorpull = system("git pull origin master")
            if (errorpull){
                print "No se ha podido pull, intervención manual requerida"
                exit 1
            }
            else {
                print "Hemos podido pull, ahora intentaremos push"
                errorpush = system("git push")
                if (errorpush){
                    print "Esto si que es raro... push falló..."
                    exit 2
                }
                else{
                    print "Hemos pusheado con exito!"
                    exit 0
                }
            }
        }
        else{
            print "Ese fue un push limpio y en regla..."
            exit 0
        }
    }
}
'
