#!/bin/sh
#Para aplicar los cambios interactivamente permitiendo comentario por fichero
awk '
BEGIN{
    FS=":"
    comando = "git commit -a --dry-run"
    while (comando|getline)
        if ($1~"modified" || $1~"new file"){
            gsub("^ *", "", $2)
            printf "Mensaje para %s: ", $2
            getline mensaje
            a[$2] = mensaje
        }
    close(commando)
    if (length(a)){
        for (i in a)
            system("git commit -m \"" a[i] "\" \"" i "\"")
        errorpush = system("git push")
        if (errorpush){
            errorpull = system("git pull origin master")
            if (errorpull){
                print "No se ha podido aplicar, intervención manual necesaria"
                exit 1
            }
            else {
                system("git push")
            }
        }
    }
}
'
